### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by WizzardMaker** [openairlinetycoon/OpenATDeluxe#12]
We should decide on a licence for the code. 

I would go for the MIT Licence as its already common among open source ports (Like CorsixTH)

**Comment by Serphentas** [comment]
Given that we do not intend on distributing the game in a non-open format/package/whatever, GPL should do the job as well.

**Comment by WizzardMaker** [comment]
I don't know if game executables fall under the "package" term as I would want to build releases for all non programmers who just want to play the game

**Comment by Serphentas** [comment]
I believe executables are not touched by GPL, so long the source is made available (as it is now). See https://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application
