### ISSUE TITLE
Compiling the GOG source code

### ISSUE THREAD

**Issue by CrossVR** [openairlinetycoon/OpenATDeluxe#17]
@WizzardMaker I'm working on reverse engineering the missing headers for the libraries in the GOG source code. I've already got everything compiling, though to get the static libraries to link I actually have to use Visual Studio C++ 6.0 (yes, the one from the 90s).

Of course just getting everything to compile is the easy part, there are a few crucial bits of header-only code not present in the static libraries that has to be reverse engineered (including the memory layout for each class). I'm making some good progress on that, my latest build can actually get in-game, though it quickly crashes on sprite corruption:

![airport](https://user-images.githubusercontent.com/2028870/62008913-5ef31600-b150-11e9-83ec-476c9efaf724.png)

I'll upload the source code to GitHub as soon as I've finished fully reverse engineering and debugging the header-only code. If you have any questions I'd be happy to answer them.

**Comment by CrossVR** [comment]
Some more progress:

![tycoons](https://user-images.githubusercontent.com/2028870/62014947-24649a00-b19f-11e9-818a-553fa32b3a82.png)

**Comment by WizzardMaker** [comment]
Great progress!

I too tried to reverse engineer the original code, but that never gave any satisfying results. I would love to see your results though!

**Comment by CrossVR** [comment]
I'm done, the complete game should be playable now except for network play. I've uploaded the source code to this repo: https://github.com/Armada651/AirlineTycoon

You'll need to set up Visual Studio C++ 6.0 to compile it: https://www.codeproject.com/Articles/1191047/Install-Visual-Studio-on-Windows

If you just want to try out a build you can download the executable here: [AT.zip](https://github.com/openairlinetycoon/OpenATDeluxe/files/3449592/AT.zip)

**Comment by CrossVR** [comment]
If you get a CD protection error simply create an empty text file called `cm.txt` in the `data` folder, that should disable to copy protection.
