### ISSUE TITLE
Missing Cursor

### ISSUE THREAD

**Issue by WizzardMaker** [openairlinetycoon/OpenATDeluxe#9]
Moved from #4 
The cursor sometimes doesn't show, even though the files are there.

Could be a Z-fighting issue with the CanvasLayer being on Layer 1 - the default layer

**Comment by Serphentas** [comment]
For some reason, I have it again now. I guess we can close this until there's a consistent way of hiding it.

**Comment by WizzardMaker** [comment]
Shouldn't happen anymore!
It probably was a bug with the image loading. This was addressed a long time ago
